name: nelab-deploy
on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  DEPLOYMENT_MANIFEST_PATH: |
    ./Manifest/frontend-deployment.yaml
    ./Manifest/frontend-service.yaml

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply Kubernetes manifests
        run: sudo k3s kubectl apply -f ${{ env.DEPLOYMENT_MANIFEST_PATH }}
