name: SonarCloud
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

env:
    ACR_RESOURCE_GROUP: Sem-6
    AZURE_CONTAINER_REGISTRY: acrworkflow1714126306763
    CLUSTER_NAME: DailyGrind
    CLUSTER_RESOURCE_GROUP: Sem-6
    CONTAINER_NAME: image-workflow-1714126306763
    DEPLOYMENT_MANIFEST_PATH: |
        ./Manifest/frontend-deployment.yaml
        ./Manifest/frontend-service.yaml

jobs:
  Analysis:
    name: Code analysis using Sonarcloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: npm test -- --coverage
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Gokay-Atalay-Sem6_Frontend
            -Dsonar.organization=software-advanced-sem6

  deploy_to_Azure:
    name: Deploy app to Azure
    permissions:
        actions: read
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    needs: Analysis
    steps:
        - uses: actions/checkout@v3
        - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
          name: Azure login
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        - uses: azure/use-kubelogin@v1
          name: Set up kubelogin for non-interactive login
          with:
            kubelogin-version: v0.0.25
        - uses: azure/aks-set-context@v3
          name: Get K8s context
          with:
            admin: "false"
            cluster-name: ${{ env.CLUSTER_NAME }}
            resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
            use-kubelogin: "true"
        - uses: Azure/k8s-deploy@v4
          name: Deploys application
          with:
            action: deploy
            images: tendeza/sem6-frontend
            manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}

